import { Injectable } from '@angular/core';

@Injectable({
  providedIn: 'root'
})
export class DataService {

  constructor() { }
  getFrontendDevelopers(){
    return [
      {
        "SrNo":1,
        "Name":"Joe",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      },
      {
        "SrNo":2,
        "Name":"Bhuvan",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      },
      {
        "SrNo":3,
        "Name":"Rachit",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      },
      {
        "SrNo":4,
        "Name":"Kailash",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      },
      {
        "SrNo":5,
        "Name":"Priyansh",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      },{
        "SrNo":6,
        "Name":"Node",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      },
      {
        "SrNo":7,
        "Name":"Prince",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      },
      {
        "SrNo":8,
        "Name":"Phantom",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      },
      {
        "SrNo":9,
        "Name":"Mohan",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      },
      {
        "SrNo":10,
        "Name":"Phonix",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      }
      
      
    
    ]
  }
  getBackendDevelopers(){
    return [
      {
        "SrNo":1,
        "Name":"Shivam",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      },
      {
        "SrNo":2,
        "Name":"Anupam",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      },
      {
        "SrNo":3,
        "Name":"Satyam",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      },
      {
        "SrNo":4,
        "Name":"Andrew",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      },
      {
        "SrNo":5,
        "Name":"Ben",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      },{
        "SrNo":6,
        "Name":"Mackinsy",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      },
      {
        "SrNo":7,
        "Name":"Ramesh",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      },
      {
        "SrNo":8,
        "Name":"Rahul",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      },
      {
        "SrNo":9,
        "Name":"Raina",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      },
      {
        "SrNo":10,
        "Name":"Mukul",
        "ProjectAllocation":"No",
        "Skills":"Java,Python",
        "Comments":"Details"
      }
    ]
  }
}
